# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prettier checks
on:
  push:
    branches: ['main', 'feat/svelte-app']
  pull_request:
    branches: ['main', 'feat/svelte-app']

jobs:
  prettier:
    name: Prettier & ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Check formatting with Prettier and ESLint
        run: npm run lint
